### ISSUE TITLE
Upgrade for Liferay 7

### ISSUE THREAD

**Issue by yuvraj11** [flarroca/sql-datatables-portlet#4]
I generally build portlets using Spring and I am not familiar with MVCPortlet, Could you please upgrade this portlet for Liferay 7 or provide instructions to do it. Much thanks!

**Comment by flarroca** [comment]
I am working on the upgrade. The plan is to bundle this portlet with https://web.liferay.com/es/marketplace/-/mp/application/81873288. 

Both use DataTables, one for SQL and the other for MDX.

**Comment by yuvraj11** [comment]
Okay. I deployed this on liferay 6 and it worked out of the box. Good job with the portlet! I have a question though: To display custom Column names, I tried the following SQL - `Select` employee_id as 'Employee Id', employee_name as 'Employee Name' from employee_` but it messes up the search and pagination. Is there any other way I can change the column names displayed?

**Comment by flarroca** [comment]
Yes, you can use the option property, it's parsed as JSON, there is a full reference in the same configuration page.
