### ISSUE TITLE
Results not updating on browser refresh

### ISSUE THREAD

**Issue by yuvraj11** [flarroca/sql-datatables-portlet#5]
When i make any changes to the results in the portlet and refresh the page, the results don't update immediately. When i refresh a couple of times, then the updated results start showing up. Looks like the request doesn't go to the controller when i refresh the page for the first time. How can i force the request to go to controller and fetch the fresh result from database every time browser is refreshed?

**Comment by flarroca** [comment]
This are the new cache options. Check the time out preference, its row count releated.
![image](https://cloud.githubusercontent.com/assets/6661751/22913484/cab7cffc-f249-11e6-8551-470d70bb7971.png)

**Comment by yuvraj11** [comment]
@flarroca Is the code checked-in for the new cache options?

Are you saying that if i change the timeout preference of row count, it will get the data from the server on page refresh? I thought the time out preference for row count was used as a timeout to make the sql query to database.

**Comment by flarroca** [comment]
See SQLDataTablePortlet.java, from line 72, and the Issue #1 SQL count not required for small tables
```java
      JSONObject json = SQLDataTableUtil.executeServerSide(driverClassName, url, userName, password, sql, where, orderBy, timeout, count, countTimeout, draw, start, length);
      if (json != null) {
         PrintWriter writer = resourceResponse.getWriter();
         writer.write(json.toString());

         int recordsTotal = json.getInt("recordsTotal", 0);
         if (recordsTotal > 0) {
            portletPreferences.setValue(SQLKeys.COUNT, String.valueOf(recordsTotal));
```

The original code use a thread with a Future interface. Yes, the current timeout is used only to create the SQL statement, which also needs configuration and has poor driver and database support. See SQLDataTableUtil.java.
```java
         connection = SQLDataSourceFactoryUtil.getConnection(driverClassName, url, userName, password);
         statement = SQLDataSourceFactoryUtil.createStatement(connection, timeout);
         resultSet = SQLDataSourceFactoryUtil.execute(statement, sql);
```
If you are in a hurry send me an email.
